site_name: Ritza Articles
site_url: https://ritza.co/articles

theme:
  name: material
  logo: assets/ritzalogo.png
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git-alt

  palette:
    - scheme: default
      primary: white

extra_css:
    - css/custom.css

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences 

plugins:
  - social

extra:
  generator: false
copyright: Produced by ritza.co - Marketing as Education.

